name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  claude-code:
    if: contains(github.event.comment.body, '@claude')
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Claude Code
        uses: anthropics/claude-code-action@v1
        with:
          anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
          
      - name: Process request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          # Claude Code will process the comment and create a PR
          claude-code process \
            --issue-comment "${{ github.event.comment.body }}" \
            --repository "${{ github.repository }}" \
            --issue-number "${{ github.event.issue.number }}"